apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auditoria-backend
  labels:
    cloud.googleapis.com/location: southamerica-west1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/cloudsql-instances: test-cloud-01-463920:southamerica-west1:auditoria-postgres
    spec:
      serviceAccountName: auditoria-runner@test-cloud-01-463920.iam.gserviceaccount.com
      containers:
      - image: southamerica-west1-docker.pkg.dev/test-cloud-01-463920/auditoria-registry/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_URL
          value: postgresql://auditoria:PLACEHOLDER_DB_PASSWORD@/auditoria_db?host=/cloudsql/test-cloud-01-463920:southamerica-west1:auditoria-postgres
        - name: KEYCLOAK_SERVER_URL
          value: KEYCLOAK_URL_PLACEHOLDER
        - name: KEYCLOAK_REALM
          value: auditoria
        - name: KEYCLOAK_CLIENT_ID
          value: Auditoria
        - name: KEYCLOAK_CLIENT_SECRET
          value: PLACEHOLDER_KEYCLOAK_SECRET
        - name: MINIO_URL
          value: https://auditoria-minio-825136167029.southamerica-west1.run.app
        - name: S3_ENDPOINT
          value: https://auditoria-minio-825136167029.southamerica-west1.run.app
        - name: S3_ACCESS_KEY
          value: PLACEHOLDER_S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          value: PLACEHOLDER_S3_SECRET_KEY
        - name: MINIO_ACCESS_KEY
          value: PLACEHOLDER_MINIO_ACCESS_KEY
        - name: MINIO_SECRET_ACCESS_KEY
          value: PLACEHOLDER_MINIO_SECRET_KEY
        - name: OPENAI_API_KEY
          value: PLACEHOLDER_OPENAI_API_KEY
        - name: OPENAI_MODEL
          value: gpt-4.1
        - name: APP_ENV
          value: production
        - name: CORS_ORIGINS
          value: "*"
        resources:
          limits:
            memory: 1Gi
            cpu: "2"
  traffic:
  - percent: 100
    latestRevision: true
